services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - WATCHFILES_FORCE_POLLING=true
    volumes:
      - ./src:/app/src:z
    depends_on:
      - keycloak
      - redis

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    command: ["start-dev"]
    ports:
      - "8080:8080"
  redis:
    image: redislabs/redismod
    ports:
      - '6379:6379'
  keycloak_db:
    image: postgres:17
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - my_db:/var/lib/postgresql/data



volumes:
  postgres_data:
  my_db: